<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260125180744 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notification_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sender VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, status_message VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, notification_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ED15DF2EF1A9D84 ON notification_log (notification_id)');
        $this->addSql('ALTER TABLE notification_log ADD CONSTRAINT FK_ED15DF2EF1A9D84 FOREIGN KEY (notification_id) REFERENCES notification (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE notification_log DROP CONSTRAINT FK_ED15DF2EF1A9D84');
        $this->addSql('DROP TABLE notification_log');
    }
}
