<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260119163822 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, sender_email VARCHAR(100) DEFAULT NULL, content TEXT NOT NULL, status VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status_updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, word_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307FE357438D ON message (word_id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FE357438D FOREIGN KEY (word_id) REFERENCES word (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE nick ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE nick ADD last_used_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE qualifier ADD last_used_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE subject ADD last_used_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE word ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE word ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FE357438D');
        $this->addSql('DROP TABLE message');
        $this->addSql('ALTER TABLE nick DROP created_at');
        $this->addSql('ALTER TABLE nick DROP last_used_at');
        $this->addSql('ALTER TABLE qualifier DROP last_used_at');
        $this->addSql('ALTER TABLE subject DROP last_used_at');
        $this->addSql('ALTER TABLE word DROP created_at');
        $this->addSql('ALTER TABLE word DROP updated_at');
    }
}
