<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251231104920 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE nick (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(100) NOT NULL, target_gender VARCHAR(10) NOT NULL, offense_level INT NOT NULL, usage_count INT NOT NULL, subject_id INT NOT NULL, qualifier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_290B2F3723EDC87 ON nick (subject_id)');
        $this->addSql('CREATE INDEX IDX_290B2F37CEE0F86E ON nick (qualifier_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_nick_properties ON nick (subject_id, qualifier_id, target_gender)');
        $this->addSql('CREATE TABLE qualifier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position VARCHAR(255) NOT NULL, usage_count INT NOT NULL, word_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_qualifier_word ON qualifier (word_id)');
        $this->addSql('CREATE TABLE subject (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usage_count INT NOT NULL, word_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_subject_word ON subject (word_id)');
        $this->addSql('CREATE TABLE word (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, label VARCHAR(50) NOT NULL, gender VARCHAR(10) NOT NULL, lang VARCHAR(10) NOT NULL, offense_level INT NOT NULL, status VARCHAR(10) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_word_slug_lang ON word (slug, lang)');
        $this->addSql('ALTER TABLE nick ADD CONSTRAINT FK_290B2F3723EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE nick ADD CONSTRAINT FK_290B2F37CEE0F86E FOREIGN KEY (qualifier_id) REFERENCES qualifier (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE qualifier ADD CONSTRAINT FK_DC7E1602E357438D FOREIGN KEY (word_id) REFERENCES word (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject ADD CONSTRAINT FK_FBCE3E7AE357438D FOREIGN KEY (word_id) REFERENCES word (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE nick DROP CONSTRAINT FK_290B2F3723EDC87');
        $this->addSql('ALTER TABLE nick DROP CONSTRAINT FK_290B2F37CEE0F86E');
        $this->addSql('ALTER TABLE qualifier DROP CONSTRAINT FK_DC7E1602E357438D');
        $this->addSql('ALTER TABLE subject DROP CONSTRAINT FK_FBCE3E7AE357438D');
        $this->addSql('DROP TABLE nick');
        $this->addSql('DROP TABLE qualifier');
        $this->addSql('DROP TABLE subject');
        $this->addSql('DROP TABLE word');
    }
}
