<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251227135126 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE qualifier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position VARCHAR(255) NOT NULL, usage_count INT NOT NULL, word_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_qualifier_word ON qualifier (word_id)');
        $this->addSql('CREATE TABLE subject (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usage_count INT NOT NULL, word_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_subject_word ON subject (word_id)');
        $this->addSql('CREATE TABLE word (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, label VARCHAR(50) NOT NULL, gender VARCHAR(10) NOT NULL, lang VARCHAR(10) NOT NULL, offense_level INT NOT NULL, status VARCHAR(10) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_word_slug_lang ON word (slug, lang)');
        $this->addSql('ALTER TABLE qualifier ADD CONSTRAINT FK_DC7E1602E357438D FOREIGN KEY (word_id) REFERENCES word (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject ADD CONSTRAINT FK_FBCE3E7AE357438D FOREIGN KEY (word_id) REFERENCES word (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE qualifier DROP CONSTRAINT FK_DC7E1602E357438D');
        $this->addSql('ALTER TABLE subject DROP CONSTRAINT FK_FBCE3E7AE357438D');
        $this->addSql('DROP TABLE qualifier');
        $this->addSql('DROP TABLE subject');
        $this->addSql('DROP TABLE word');
    }
}
