<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123142153 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sender_email VARCHAR(100) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sender_email VARCHAR(100) NOT NULL, reason TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, nick_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C42F7784C2ABD7E9 ON report (nick_id)');
        $this->addSql('CREATE TABLE suggestion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, creator_email VARCHAR(100) DEFAULT NULL, label VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784C2ABD7E9 FOREIGN KEY (nick_id) REFERENCES nick (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT fk_b6bd307fe357438d');
        $this->addSql('DROP INDEX idx_b6bd307fe357438d');
        $this->addSql('ALTER TABLE message ADD recipient_email VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE message ADD subject TEXT NOT NULL');
        $this->addSql('ALTER TABLE message DROP sender_email');
        $this->addSql('ALTER TABLE message DROP word_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784C2ABD7E9');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE suggestion');
        $this->addSql('ALTER TABLE message ADD sender_email VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE message ADD word_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE message DROP recipient_email');
        $this->addSql('ALTER TABLE message DROP subject');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT fk_b6bd307fe357438d FOREIGN KEY (word_id) REFERENCES word (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_b6bd307fe357438d ON message (word_id)');
    }
}
